# Generated by Django 4.0.4 on 2022-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': ' Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
        migrations.RenameField(
            model_name='train',
            old_name='arrival_time',
            new_name='Время отправления',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='departure_time',
            new_name='Время прибытия',
        ),
        migrations.AddField(
            model_name='train',
            name='Задержан до',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='Статус',
            field=models.CharField(choices=[(None, 'Выберите статус'), ('l', 'Идет посадка'), ('a', 'Прибытие'), ('s', 'Отправлен'), ('d ', 'Задержан до'), ('c ', 'Отменен')], max_length=255),
        ),
    ]
