# Generated by Django 4.0.4 on 2022-05-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_city_options_alter_train_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='Задержан до',
            new_name='Задержан',
        ),
    ]
