# Generated by Django 4.0.4 on 2022-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_alter_train_options_remove_train_время отправления_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='platform_number',
            field=models.PositiveIntegerField(verbose_name='Номер платформы'),
        ),
        migrations.AlterField(
            model_name='train',
            name='Номер',
            field=models.CharField(max_length=255),
        ),
    ]
