# Generated by Django 4.0.4 on 2022-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_alter_train_platform_number_alter_train_номер'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Наименование',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
