# Generated by Django 4.0.4 on 2022-05-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_remove_city_наименование_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='Номер',
        ),
        migrations.AddField(
            model_name='train',
            name='num',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
