# Generated by Django 4.0.4 on 2022-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_remove_train_номер_train_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите статус'), ('l', 'Идет посадка'), ('a', 'Прибытие'), ('s', 'Отправлен'), ('d ', 'Задержан'), ('c ', 'Отменен')], default=(None, 'Выберите статус'), max_length=2, verbose_name='Статус'),
        ),
    ]
